image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - export REACT_APP_SECRET_API_KEY=$API_KEY # set REACT_APP variables before build command
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script: npm test
