image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - export REACT_APP_DB_URL=$DB_URL # set REACT_APP variables before build command
    - export REACT_APP_COOKIE_SECRET=$COOKIE_SECRET
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script: npm test
